Fixing null columns issue
Automattic/target-parquet pull request #4
Opened 2022-12-19 19:44 UTC by joaopamaral

The PR https://github.com/Automattic/target-parquet/pull/2 included a code to extract the object nested fields even if the column is null, the issue is that the check can replace some fields that have the same field name in nested objects making some undesirable replacements.

To avoid that, we added a code to merge an empty record (created with all schema fields) with the real values in the record.

2022-12-19 19:53 UTC, joaopamaral commented on target_parquet/helpers.py
> -             'key_7__key_9': None
This inclusion will be done outside the function (when merge with empty record).

2022-12-21 11:01 UTC, Khrol commented on target_parquet/__init__.py
> +                    flattened_record = schema.fromkeys(schema.keys(), None) | flatten(message["record"], schema)
I think you should just include this logic into `flatten` method.

2022-12-21 11:02 UTC, Khrol commented on test/test_helpers.py
> +    output = flat_schema.fromkeys(flat_schema.keys(), None) | flatten(in_dict, flat_schema)
This test is weird. You should improve `flatten` method to do what you need and test the method without extra tricks just to keep test green.

2022-12-21 11:03 UTC, Khrol commented on test/test_persist.py
> +    return pd.DataFrame(
Update tests to demo some concrete behavior. Given this schema in place, it's hard to understand what's tested here.

2022-12-21 11:04 UTC, Khrol requested changes
Please make the changes more local and clearly tested.

2022-12-21 13:38 UTC, joaopamaral commented on target_parquet/helpers.py
> +    if not parent_key:
Since this method is called recursively, I've included the empty record only in the first call

2022-12-21 13:41 UTC, joaopamaral commented on target_parquet/helpers.py
> +    items = {} if parent_key else flat_schema.fromkeys(flat_schema.keys(), None)
Since this method is called recursively, I've included the empty record only in the first call

2022-12-21 13:49 UTC, Khrol approved these changes
Nice. Old tests are not affected - so the chance of regression is less. LGTM.

2022-12-21 14:51 UTC, merged